version: '0.1'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # you must create a '.env' file similar to the format in '.env.sample'
    env_file: .env
    environment:
      # this is used for database_setup to use "db" as the host instead of "localhost"
      DOCKERCOMPOSE: 1
      # NOTE: in production, change these to use environment variables for credentials
      # stored in a .env file
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-integrated_vision_inspection_system}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shrdc}
    ports:
      - 5432:${POSTGRES_PORT:-5432}

  app:
    image: integrated_vision_inspection_system
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      DEBUG: ${DEBUG:-False}
    # care that the `myuser` name is used in the Dockerfile
    # this volume directly binds to the directory obtained by `appdirs` library 
    # in Python in path_desc.py
    volumes:
      - app-data:/home/myuser/.local/share/integrated_vision_inspection_system
    # Note that this port is based on the .streamlit/config.toml file
    ports:
      - 8502:8502
    # use this to create/start the database first before creating/booting up this image
    depends_on:
      - db

volumes:
  postgres-data:
  app-data: